### ISSUE TITLE
This resource is no longer available under v1 APIs

### ISSUE THREAD

**Issue by rikmendes** [mapkyca/known-linkedin#24]
![image](https://user-images.githubusercontent.com/12155003/58323566-a5608780-7e24-11e9-94e5-904f4680080d.png)

It seems the current state of the Linkedin plugin can't work with either v1 or v2 of Linkedin API
just letting you know.

I have created a new app that use v2 of the API, the connection part seems to go just fine but when the callback needs to return to the website it display this message above. 

Using Version: 0.9.9-a+2019042401

(from your latest package)

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/KnownLinkedin/issues/24" class="u-in-reply-to"></a>Ahh... thanks for the heads up. I'll try and find some time to take a look at the new API...

(PRs welcome of course ;) )

**Comment by rikmendes** [comment]
I wish I could help with PR's, but I'm just not a developer :/ by the way amazing work with Known template cleanup.. The new dashboard is neat, love the way configuration menu's are now sleek! Sent from my mobile, excuse for brevity

**Comment by rmdes** [comment]
Any update on this ?

**Comment by mapkyca** [comment]
Yeah, looks like LinkedIn changed their TOS for their apis which makes maintaining this somewhat pointless.
