### ISSUE TITLE
Cannot access private property Idno\Core\Idno::$config

### ISSUE THREAD

**Issue by lindner** [mapkyca/known-linkedin#25]
Looks like this plugin needs to be updated for latest changes to core.

Error message when attempting to set the oauth key/secret:

`Cannot access private property Idno\Core\Idno::$config`

**Comment by lindner** [comment]
[ same issue on github plugin too...]

**Comment by mapkyca** [comment]
Thanks for the heads up, I'll try and look at this when I can.

As it happens, I'm pretty much considering Linkedin as dead - they changed their api recently, and locked down who can have access etc. Looks like it's something that individuals can no longer use to POSSE

**Comment by lindner** [comment]
It appears I can create a LinkedIn "page" and enable the APIs.  I also know the devrel contact over there so I might be able to see if there's a way to enable Indieweb functionality..
